"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1:  1
 3:  1,3
 6:  1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math

def numDivs1(num):
    divs = 0
    limit = int(num/2.0)
    if num == 1:
        return 1
    else:
        for x in range(limit, 0, -1):
            if num % x == 0:
                divs += 1
    return divs+1   #for num

def numDivs2(num):
    divs = 0
    limit = int(math.floor(math.sqrt(num)))
    for x in range(limit, 0, -1):
        if num % x == 0:
            if num/x == math.sqrt(num):
                divs += 1
            else:
                divs += 2
    return divs

def findFactors(num):
    facts = []
    for x in range(1,num+1):
        if num%x == 0:
            facts.append(x)
    return facts


def findTriWithDivs(goalDiv):
    curDiv = 0
    curNum = 0
    curTri = 0
    maxDiv = 0
    while goalDiv > curDiv:
        curNum += 1
        curTri += curNum
        curDiv = numDivs2(curTri)
        if curDiv > maxDiv:
            maxDiv = curDiv
    return (curNum, curTri, curDiv, goalDiv)



print findTriWithDivs(500)










